sonar.organization=marandadev_laboratorio-final
sonar.projectKey=marandadev
sonar.projectName=Movies DevSecOps
sonar.sources=.
sonar.language=javascript
sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarcloud.io